name: ocuscan_flutter
description: Flutter version of the OcuScan app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.6
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  go_router: ^13.2.1
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  ionicons: ^0.2.2
  network_info_plus: ^6.1.4
  path: ^1.8.3
  provider: ^6.1.2
  sqflite: ^2.3.2
  supabase_flutter: ^2.4.5
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  youtube_player_flutter: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  file_selector: ^1.0.0
  printing: ^5.11.0
flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/patient-registration.png
    - assets/illustrations/image-capture.png
    - assets/illustrations/analysis.png
    - assets/illustrations/history.png
    - assets/google_logo.png
    - assets/retina.jpeg
    - assets/icon.png
    - assets/fonts/Noto_Sans/static/NotoSans_Condensed-Bold.ttf
